name: "netflix_elt"
version: "1.0.0"
config-version: 2

profile: "netflix_elt"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflix_elt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      analysis:
        +materialized: table
